### ISSUE TITLE
How do you set your data.yaml nc =7? I thought roboflow will detect 59 classes automatically?

### ISSUE THREAD

**Issue by MheadHero** [manaporkun/Trash-Filter-YOLOV5#1]
Hi, I am doing yolov5 project using taco datasets too. How do you set your data.yaml nc =7? I thought roboflow will detect 59 classes automatically? I wanted to use it 28 supercategory classes.

**Comment by manaporkun** [comment]
Hi,

Thank you for reaching out. I used [labelImg ](https://github.com/tzutalin/labelImg) to create classes and labels. It's a great tool. However, you can also try Roboflow's labeling interface. I recommend checking their documentation for this: [The Labeling Interface](https://docs.roboflow.com/annotate/the-labeling-interface).
